version: "3"

services:
  postgres:
    image: postgres

    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    depends_on:
      - postgres
    image: postgres/example-postgres-app
    build:
      context: ./api
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB",
        "spring.datasource.username"  : "$POSTGRES_USER",
        "spring.datasource.password"  : "$POSTGRES_PASSWORD"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  frontend:
#    depends_on:
#      - api
    image: frontend
    build: ./frontend
    ports:
      - "8081:80"
    environment:
      - "API_BASE_URL=localhost:${SPRING_LOCAL_PORT}"
